### ISSUE TITLE
Quotation marks and brackets duplicated in welcome message text box

### ISSUE THREAD

**Issue by boothym** [osmbe/osm-welcome-belgium#267] opened 2021-12-10 17:30 UTC
Typing a welcome message to a user - if you press **', ", or (** you get a second **' " )** appear.

**Comment by jbelien** [comment] 2021-12-11 14:18
Hello @boothym ,

"It's a feature, not a bug." 😄 

The message uses [Markdown](https://daringfireball.net/projects/markdown/) and the "text editor" is made to highlight Markdown features (link, bold, italic, ...).
It's also add a few features, like closing a parenthesis or a quotation mark (using [CodeJar](https://medv.io/codejar/)).

**Comment by boothym** [comment] 2021-12-14 19:38
Right, but if you are writing a message with an apostrophe or quotation mark and don't notice this feature then you'll have extra punctuation where it is not needed. 

Also, once I pressed the "send message" it took me to the OSM message user page. However I don't think OSM supports markdown anyway?

**Comment by jbelien** [comment] 2021-12-15 05:46
> Right, but if you are writing a message with an apostrophe or quotation mark and don't notice this feature then you'll have extra punctuation where it is not needed.

I do agree than closing a single quote (apostrophe) doesn't make much sense in a text but I still find convenient that double quote, parenthesis, brackets, ... are automatically closed.

> Also, once I pressed the "send message" it took me to the OSM message user page. However I don't think OSM supports markdown anyway?

The goal of this tool is indeed to use osm.org internal messaging system.
That system do support Markdown using kramdown library.

![image](https://user-images.githubusercontent.com/1150563/146130376-25e94b8c-e8a8-4b80-aa01-fc9ce71be259.png)

**Comment by boothym** [comment] 2021-12-15 12:34
> The goal of this tool is indeed to use osm.org internal messaging system.
> That system do support Markdown using kramdown library.

But using ' ' and "" "" for bold or italics does not work in kramdown - you need to use * * or ** **.

**Comment by jbelien** [comment] 2021-12-15 12:45
> But using ' ' and "" "" for bold or italics does not work in kramdown - you need to use * * or ** **.

Indeed, __bold__ is `**...**` (or `__...__`) and _italic_ is `*...*` (or `_..._`).
That's defined by the Markdown format (https://daringfireball.net/projects/markdown/syntax).

**Closed as completed** 2022-01-09 16:46 UTC
Labels: question
