### ISSUE TITLE
Please update the welcom tool "Belgium" thx

### ISSUE THREAD

**Issue by Jakkajakka** [osmbe/osm-welcome-belgium#1382] opened 2024-06-12 17:38 UTC
Last update: 14 days ago

**Comment by bxl-forever** [comment] 2024-08-02 14:22
Duplicate of issue #1344

**Comment by jbelien** [comment] 2024-09-08 12:21
As @bxl-forever said, this is a duplicate of #1344 ; join discussion on #1413

**Closed as not planned by jbelien** 2024-09-08 12:21 UTC
